package jeu;
/**
 * une sortie possible dans le jeu 
 * */
public enum Sortie {
	
	DEVANTFORET,PLAGE,DEVANTGROTTE,GROTTE,BOUTEILLE,FORET,BOIS,COCO,RADEAU,RAMASSER,ILESAINTE,ILEOBSC,ILEMIRAGE,BANANE,FORET2,CARTE,COBRA,ANANAS,AVANCER,DEVANTCOFFRE,COFFRE;
}